#!/usr/bin/env bash
#!/bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Using SCP to transfer the file securely to the remote server.
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
