#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web-01 and web-02 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 430805-web-01 18.233.64.111:80 check
   server 430805-web-02 54.144.152.108:80 check


" >> /etc/haproxy/haproxy.cfg

service haproxy start
